# Required:

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_add = '''
source ~/.config/nvim_local/coc.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'tomasr/molokai'
